version: '3.9'
services:
  nginx:
    image: nginx:latest
    container_name: todo-nginx
    ports:
      - 80:80
    volumes:
      - ./src/:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - php
  php:
    image: php:8.2-fpm
    container_name: todo-php
    volumes:
      - ./src/:/var/www/html